server:
  port: 8081
spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=UTF-8
    username: root
    password: 123
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  thymeleaf:
    cache: false
    enabled: false
#  redis:
#    host: 192.168.135.129
#    timeout: 1000